# -*- Makefile -*-

all:
	clear;
	# Welcome to Week 5 Coding Assignments.
	# To compile Q0 (for example), write the command:
	# 	'make Q0' (without quotes)
	# into the command prompt and this will create
	# the executable 'Q0Main' in the current directory.
	# You can run this executable using the command
	#	'./Q0Main' (without quotes)
	#
	# You can run the command 'make Q0' any number of times you like.
	# Good luck!

Q1: 1_leftrotation.c
	gcc 1_leftrotation.c -o Q1Main

Q2: 2_swap.c
	gcc 2_swap.c -o Q2Main

Q3: 3_vendingmachine3.c
	gcc 3_vendingmachine3.c -o Q3Main

Q4: 4_selectionsort.c
	gcc 4_selectionsort.c -o Q4Main

Q5: 5_water.c
	gcc 5_water.c -o Q5Main

Q6: 6_birds.c
	gcc 6_birds.c -o Q6Main

Q7: 7_samestring.c
	gcc 7_samestring.c -o Q7Main

Q8: 8_nochange.c
	gcc 8_nochange.c -o Q8Main
