# -*- Makefile -*-

all:
	clear;
	# Welcome to Week 6 Coding Assignments.
	# To compile Q0 (for example), write the command:
	# 	'make Q0' (without quotes)
	# into the command prompt and this will create
	# the executable 'Q0Main' in the current directory.
	# You can run this executable using the command
	#	'./Q0Main' (without quotes)
	#
	# You can run the command 'make Q0' any number of times you like.
	# Good luck!
Q6: 6_ztests.c
	gcc 6_ztests.c -o Q6Main
